//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JRC_PastMe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JRC_PastMe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EC_JRC_logo_vertical_EN_pos_transparent_background {
            get {
                object obj = ResourceManager.GetObject("EC-JRC-logo_vertical_EN_pos_transparent-background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123456
        ///12345
        ///123456789
        ///password
        ///iloveyou
        ///princess
        ///1234567
        ///rockyou
        ///12345678
        ///abc123
        ///nicole
        ///daniel
        ///babygirl
        ///monkey
        ///lovely
        ///jessica
        ///654321
        ///michael
        ///ashley
        ///qwerty
        ///111111
        ///iloveu
        ///000000
        ///michelle
        ///tigger
        ///sunshine
        ///chocolate
        ///password1
        ///soccer
        ///anthony
        ///friends
        ///butterfly
        ///purple
        ///angel
        ///jordan
        ///liverpool
        ///justin
        ///loveme
        ///fuckyou
        ///123123
        ///football
        ///secret
        ///andrea
        ///carlos
        ///jennifer
        ///joshua
        ///bubbles
        ///1234567890
        ///superman
        ///hannah
        ///amanda
        ///loveyou
        ///pretty
        ///basketball
        ///andrew
        ///angels
        ///tweety
        ///flower [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string listWorstPwrs_Windows {
            get {
                return ResourceManager.GetString("listWorstPwrs_Windows", resourceCulture);
            }
        }
    }
}
